version: '3'
services:
  app:
    build:
      context: ./docker/construct_app
      dockerfile: Dockerfile-express
    image: express-app
    container_name: express-app
    ports:
      - 3000:3000
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm start]
